name: audit+install

on:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        fetch-depth: 1

    - name: Install Homebrew
      if: matrix.os == 'ubuntu-latest'
      uses: Homebrew/actions/setup-homebrew@master

    - name: Update Homebrew
      if: matrix.os == 'macos-latest'
      run: |
        brew update --auto-update

    - name: Install Go
      if: matrix.os == 'macos-latest'
      run: |
        brew unlink go@1.21
        brew link --overwrite go

    - name: Tap Repository
      run: brew tap idleberg/asahi

    - name: Audit Formulas
      run: |
        for file in ./Formula/*.rb
        do
          echo "Auditing $file"
          brew audit idleberg/asahi/$(basename ${file%.rb}) --online
        done

    - name: Install Formulas
      run: |
        for file in ./Formula/*.rb
        do
          echo "Installing $file"
          brew install idleberg/asahi/$(basename ${file%.rb}) --build-from-source
        done
